/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.code.calculadora;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pc-9
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    private String concatenar = "";
    public ArrayList<Double> numero = new ArrayList<>();
    private String operacion = "";
    private String valor;
    double resultado = 0;
    String estado;
    double valorNumerico;
    double total;

    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtContenido = new javax.swing.JTextField();
        btnOff = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnAc = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnDoble = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        txtMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOff.setText("OFF");
        btnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffActionPerformed(evt);
            }
        });

        btnDel.setText("DEL");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnAc.setText("AC");
        btnAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcActionPerformed(evt);
            }
        });

        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnSiete.setText("7");
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });

        btnOcho.setText("8");
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });

        btnNueve.setText("9");
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });

        btnMulti.setText("*");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnCuatro.setText("4");
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });

        btnCinco.setText("5");
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnSeis.setText("6");
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });

        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnUno.setText("1");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        btnDos.setText("2");
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });

        btnTres.setText("3");
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnCero.setText("0");
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });

        btnDoble.setText("00");
        btnDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDobleActionPerformed(evt);
            }
        });

        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDoble, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMulti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIgual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDoble, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        String texto = txtContenido.getText();
        if(!texto.equals(String.valueOf(total))&&!operacion.equals("")&&!concatenar.isEmpty()&&!numero.isEmpty()){
            if(texto.isEmpty()){
                txtContenido.setText("");

            }else{
                txtContenido.setText(texto.substring(0, texto.length()-1));
            }
            if(!concatenar.isEmpty()){
                concatenar = concatenar.substring(0, concatenar.length()-1); 
            }else{
                concatenar = "";
            }
            if (operacion.equals("resultado")){
                txtMostrar.setText(String.valueOf(numero.get(0)));
            }else{
                txtMostrar.setText(String.valueOf(numero.get(0)+ operacion));
            }
            
        }else{
            txtContenido.setText("");
            concatenar = "";
            txtMostrar.setText(String.valueOf(total));
        }
        
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDobleActionPerformed
        if(!concatenar.isEmpty()){
        btnDoble.setText("00");
        concatenar += btnDoble.getText();
        }
        txtContenido.setText(concatenar);
        operacion = "";
    }//GEN-LAST:event_btnDobleActionPerformed

    private void btnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOffActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        
        btnNueve.setText("9");
        concatenar += btnNueve.getText();
        txtContenido.setText(concatenar);
        
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcActionPerformed
        txtMostrar.setText("");
        txtContenido.setText("");
        resultado=0;
        concatenar="";
        total=0;
        numero.clear();
    }//GEN-LAST:event_btnAcActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        estado = "*";
        if (numero.isEmpty()&&!concatenar.isEmpty()){
            asignacionInicial();     
        }else if(numero.size()==1&&concatenar.isEmpty()&&operacion.equals("resultado")){
            asignacionResultado();
        }else if(!numero.isEmpty()&&!concatenar.isEmpty()&&operacion.equals("*")){
            asignacionNumero();
            valor = String.valueOf(numero.get(0))+"*"+ concatenar + "=" ;
            resultado = numero.get(0)*numero.get(1);
            outResultado();
        }else if(numero.size()==1 && concatenar.isEmpty()){
            asignacionResultado();
        }else if(!numero.isEmpty()&&!concatenar.isEmpty()&&operacion.equals("resultado")){
            asignacionNumero();
            valor = String.valueOf(numero.get(0))+"*"+ concatenar + "=" ;
            resultado = numero.get(0)*numero.get(1);
            estado="";
            outResultado();
            
        }
        if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("+")){
            
            btnSuma.doClick();
            operacion="*";
            goToNewOperation();
            
        }else if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("-")){
          
            btnResta.doClick();
            operacion="*";
            goToNewOperation();
            
        }else if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("/")){
            
            btnDividir.doClick();
            operacion="*";
            goToNewOperation();
            
        }
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        
        btnUno.setText("1");
        concatenar += btnUno.getText();
        txtContenido.setText(concatenar);
        
        

    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        
        btnDos.setText("2");
        concatenar += btnDos.getText();
        txtContenido.setText(concatenar);
        
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        
        btnTres.setText("3");
        concatenar += btnTres.getText();
        txtContenido.setText(concatenar);
        
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        
        btnCuatro.setText("4");
        concatenar += btnCuatro.getText();
        txtContenido.setText(concatenar);
        
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        
        btnCinco.setText("5");
        concatenar += btnCinco.getText();
        txtContenido.setText(concatenar);
        
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
       
        btnSeis.setText("6");
        concatenar += btnSeis.getText();
        txtContenido.setText(concatenar);
        
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        
        btnSiete.setText("7");
        concatenar += btnSiete.getText();
        txtContenido.setText(concatenar);
        
        
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        
        btnOcho.setText("8");
        concatenar += btnOcho.getText();
        txtContenido.setText(concatenar);
        
        
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        estado = "+";
        if (numero.isEmpty()&&!concatenar.isEmpty()){
            asignacionInicial();            
        }else if(numero.size()==1&&concatenar.isEmpty()&&operacion.equals("resultado")){
            asignacionResultado();
        }else if(!numero.isEmpty()&&!concatenar.isEmpty()&&operacion.equals("+")){
            asignacionNumero();
            valor = String.valueOf(numero.get(0))+estado+ concatenar + "=" ;
            resultado = numero.get(0)+ numero.get(1);
            outResultado();
        }else if(numero.size()==1 && concatenar.isEmpty()){
            asignacionResultado();
        }else if(!numero.isEmpty()&&!concatenar.isEmpty()&&operacion.equals("resultado")){
            asignacionNumero();
            valor = String.valueOf(numero.get(0))+"+"+ concatenar + "=" ;
            resultado = numero.get(0)+numero.get(1);
            estado="";
            outResultado();  
        }
        if(numero.size()==1 && !concatenar.isEmpty()&&operacion.equals("-")){
            
            btnResta.doClick();
            operacion="+";
            goToNewOperation();
            
        }else if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("*")){
            
            btnMulti.doClick();
            operacion="+";
            goToNewOperation();
            
        }else if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("/")){
            
            btnDividir.doClick();
            operacion="+";
            goToNewOperation();
            
        }
        
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        switch (operacion) {
            case "+" -> {
                valorNumerico = Double.parseDouble(concatenar);
                total = numero.get(0) + valorNumerico;
                txtContenido.setText(String.valueOf(total));
                txtMostrar.setText(String.valueOf(numero.get(0))+"+" + String.valueOf(valorNumerico) + "=" );
                numero.clear();
                concatenar = "";
                numero.add(total);
                operacion = "resultado";
            }
            case "-" -> {
                valorNumerico = Double.parseDouble(concatenar);
                total = numero.get(0) - valorNumerico;
                txtContenido.setText(String.valueOf(total));
                txtMostrar.setText(String.valueOf(numero.get(0))+"-" + String.valueOf(valorNumerico) + "=");
                numero.clear();
                concatenar = "";
                numero.add(total);
                operacion="resultado";
            }
            case "*" -> {
                valorNumerico = Double.parseDouble(concatenar);
                total = numero.get(0) * valorNumerico;
                txtContenido.setText(String.valueOf(total));
                txtMostrar.setText(String.valueOf(numero.get(0))+"*" + String.valueOf(valorNumerico) + "=");
                numero.clear();
                concatenar = String.valueOf(total);
                numero.add(total);
                operacion="resultado";
            }
                
            case "/" -> {
                valorNumerico = Double.parseDouble(concatenar);
                total = numero.get(0) / valorNumerico;
                txtContenido.setText(String.valueOf(total));
                txtMostrar.setText(String.valueOf(numero.get(0))+"/" + String.valueOf(valorNumerico) + "=");
                numero.clear();
                concatenar = String.valueOf(total);
                numero.add(total);
                operacion="resultado";
            }
            
            case "resultado" -> {
                txtContenido.setText(String.valueOf(total));
                txtMostrar.setText(String.valueOf(total));
            }
            default ->{
                
            }
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        estado = "-";
        if (numero.isEmpty()&&!concatenar.isEmpty()){
            asignacionInicial();            
        }else if(numero.size()==1&&concatenar.isEmpty()&&operacion.equals("resultado")){
            asignacionResultado();
        }else if(!numero.isEmpty()&&!concatenar.isEmpty()&&operacion.equals("-")){
            asignacionNumero();
            valor = String.valueOf(numero.get(0))+"-"+ concatenar + "=" ;
            resultado = numero.get(0)- numero.get(1);
            outResultado();
        }else if(numero.size()==1 && concatenar.isEmpty()){
            asignacionResultado();
        }
        if(!numero.isEmpty()&&!concatenar.isEmpty()&&operacion.equals("resultado")){
            
            asignacionNumero();
            valor = String.valueOf(numero.get(0))+"-"+ concatenar + "=" ;
            resultado = numero.get(0)-numero.get(1);
            estado="";
            outResultado();      
        }
        if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("+")){
            
            btnSuma.doClick();
            operacion="-";
            goToNewOperation();
           
        }else if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("*")){
            
            btnMulti.doClick();
            operacion="-";
            goToNewOperation();
            
        }else if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("/")){
            
            btnDividir.doClick();
            operacion="-";
            goToNewOperation();
            
        }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        estado = "/";
        if(numero.get(0)!=0){
            if (numero.isEmpty()&&!concatenar.isEmpty()){
            asignacionInicial();
            
        }else if(numero.size()==1&&concatenar.isEmpty()&&operacion.equals("resultado")){
            asignacionResultado();
        }else if(!numero.isEmpty()&&!concatenar.isEmpty()&&operacion.equals("/")){
            asignacionNumero();
            valor = String.valueOf(numero.get(0))+"/"+ concatenar + "=" ;
            resultado = numero.get(0)/ numero.get(1);
            outResultado();
        }else if(numero.size()==1 && concatenar.isEmpty()){
            asignacionResultado();
        }else if(!numero.isEmpty()&&!concatenar.isEmpty()&&operacion.equals("resultado")){
            
            asignacionNumero();
            valor = String.valueOf(numero.get(0))+"/"+ concatenar + "=" ;
            resultado = numero.get(0)/numero.get(1);
            estado="";
            outResultado();
            
        }
        if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("+")){
            
            btnSuma.doClick();
            operacion="/";
            goToNewOperation();
            
        }else if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("*")){
            
            btnMulti.doClick();
            operacion="/";
            goToNewOperation();
           
        }else if(numero.size()==1 &&!concatenar.isEmpty()&&operacion.equals("-")){
            
            btnResta.doClick();
            operacion="/";
            goToNewOperation();
            
        }
        }JOptionPane.showMessageDialog(null, "No es posible dividir en cero");
        txtMostrar.setText("");
        txtContenido.setText("");
        numero.clear();
        concatenar="";
        
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        if(!concatenar.isEmpty()){
            btnCero.setText("0");
            concatenar += btnCero.getText();

            txtContenido.setText(concatenar);
        }
        
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if(concatenar.contains(".")){
            txtContenido.setText(concatenar);
        }else{
            btnPunto.setText(".");
            concatenar += btnPunto.getText();
            txtContenido.setText(concatenar);
        }
        if(concatenar.isEmpty()){
            btnPunto.setText("0.");
            concatenar += btnPunto.getText();
            txtContenido.setText(concatenar);
        }
       
    }//GEN-LAST:event_btnPuntoActionPerformed

    public void asignacionInicial(){
        asignacionNumero();
        valor = concatenar + estado;
        txtMostrar.setText(valor);
        operacion = estado;
        concatenar = "";     
    }
    
    public void asignacionNumero(){
        valorNumerico = Double.parseDouble(concatenar);
        numero.add(valorNumerico);
    }
    
    public void asignacionResultado(){
        valor = String.valueOf(numero.get(0))+ estado;
        txtMostrar.setText(valor);
        operacion = estado;
        concatenar = "";
        System.out.println(operacion);
    }
    
    public void outResultado(){
        txtContenido.setText(String.valueOf(resultado));
        txtMostrar.setText(String.valueOf(resultado)+estado);
        numero.clear();
        numero.add(resultado);
        operacion = estado;
        concatenar="";
        
    }
    
    public void goToNewOperation(){
        txtContenido.setText(String.valueOf(resultado));
        txtMostrar.setText(String.valueOf(resultado)+operacion);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAc;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnDoble;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnOff;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtContenido;
    private javax.swing.JLabel txtMostrar;
    // End of variables declaration//GEN-END:variables
}
